import { app } from "./runtime.js";
import "./sentry.js";
import "./usage.js";
import "./data/body.js";
import "./data/state.js";
import "./shared/icons.js";
import "./shared/analyze.js";
import "./pages/insights.js";
import "./shared/cloud.js";
import "./shared/profile.js";
import "./pages/goals.js";
import "./pages/session.js";
import "./pages/progress.js";
import "./pages/food.js";
import "./pages/cardio.js";
import "./shared/platform.js";
import "./shared/muscles.js";
import "./shared/widgets.js";
import "./pages/workouts.js";
import "./pages/privacy.js";
import "./pages/settings.js";
import "./shared/brief.js";
import "./shared/weekly.js";
import "./pages/home.js";
import "./shell/workout.js";
import "./shell/timer.js";
import "./shell/actions.js";
import "./shell/pager.js";

window.app = app;
app.render();
if (app.noteTab) app.noteTab(app.ui.tab || "home");
app.initCloud();
